### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by ceoshikhar** [pvarentsov/sudoku#1]
![image](https://user-images.githubusercontent.com/62669971/124497560-a1134080-ddd8-11eb-8649-8bfcaa75fb96.png)

Having syntax error although the source code and lint show no issues.

**Comment by pvarentsov** [comment]
Hi @ceoshikhar!

In this project [tsconfig.json](https://github.com/pvarentsov/sudoku/blob/main/tsconfig.json#L16) uses ES2020 target. I think your node.js version does't support [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) feature. Сould you please try to upgrade the node.js version to `>=14`? If it helps, I will change the target, for example to ES2015.

**Comment by ceoshikhar** [comment]
Yep! you were right, I have to upgrade the nodejs version. Worked perfectly fine. Thank you for quick response. Sent you a connection request on LinkedIn. Loved your Clean Architecture Typescript project.
